api/urls.py
from django.urls import path
# from api.views import BookReviewDetailAPIView,BookReviewsApiView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet
router = DefaultRouter()

app_name = "api"

router.register('reviews', BookReviewViewSet, basename='review')

urlpatterns = router.urls

# urlpatterns = [
#     path("reviews/", BookReviewsApiView.as_view(), name='review-list'),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name='review-detail'),
# ]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView,AddReviewView,EditReviewView,ConfirmDeleteView,DeleteReviewView,\
    AuthorinformView

app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(),name='reviews'),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteView.as_view(), name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete-review"),
    path("<int:book_id>/inform/", AuthorinformView.as_view(), name="inform"),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path("books/", include('books.urls')),
    path('', landing_page, name="landing_page"),
    path('home', home_page, name="home_page"),
    path("api/", include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, ProfileView, LogOutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
<html lang="en">
    <meta charset="UTF-8">
    <title >{% block title %}Goodreads Clone {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet"  type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body class="mx-4">


<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{% url 'home_page' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{% url 'books:list' %}">Books</a>
        </li>
      </ul>
        <div >
            {% if request.user.is_authenticated %}
                <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle bg-primary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.user.username }}
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                      </div>
                    </div>
            {% else %}
                <a class="btn btn-primary" href="{% url 'users:login' %}">Login</a>
            {% endif %}

        </div>
    </div>


  </div>
</nav>

<div class="container">
    {% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    {% endif %}

{% block content %}{% endblock %}
</div>







<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}

{% block content %}
  <h3>All reviews</h3>
  <style>
    .profile-pic {
    width: 90px;
    height: 90px;
    border-radius: 50%;
}
  </style>
  {% for review in page_obj %}
      <div class="container posts-content">
      <div class="row">
          <div class="col-lg-6">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="media mb-3">
                    <img class="profile-pic" src="{{ review.user.profile_picture.url }}" alt="">
                    <div class="media-body ml-3">
                      <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars ⭐️ <br>
                      <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                    </div>
                  </div>

                  <p>
                    {{ review.comment | truncatechars:250}}
                  </p>
                  <img class="cover-pic center" src="{{ review.book.cover_picture.url }}" alt="">
                </div>

              </div>
          </div>

      </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo;first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="" class="page-link" >{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}">next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}">last&raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/landing.html
{% extends "base.html" %}

{% block content %}
    <h1>Landing Page</h1>
    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.In December 2007, the site had 650,000 members and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads, and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.

    By July 2019, the site had 90 million members
    </p>
{% endblock %}